name: Inject Python Snippet

on:
  push:
    paths:
      - 'snippets/*.py'

  workflow_call:

jobs:
  inject-snippet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set target .md from latest .py
        run: |
          LATEST_PY=$(find snippets -name '*.py' -printf '%T@ %p\n' | sort -nr | cut -d' ' -f2- | head -n1)
          BASENAME=$(basename "$LATEST_PY" .py)
          TARGET_MD=$(jq -r --arg key "$BASENAME" '.[$key] // empty' mappings/target_md-map.json)
          if [ -z "$TARGET_MD" ]; then
            TARGET_MD="articles/tech-algo-${BASENAME%%_*}.md"
          fi
          echo "LATEST_PY=$LATEST_PY" >> $GITHUB_ENV
          echo "BASENAME=$BASENAME" >> $GITHUB_ENV
          echo "TARGET_MD=$TARGET_MD" >> $GITHUB_ENV

      - name: Inject Python Snippet
        run: |
          python scripts/inject-snippet.py "$BASENAME" "$TARGET_MD"

      - name: Execute and inject result
        run: |
          python scripts/inject-result.py "$BASENAME" "$TARGET_MD" "$LATEST_PY"

      - name: Commit and Push if Changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "$TARGET_MD"
          git diff --cached --quiet || git commit -m "Auto update article with new snippet"
          git push
          
