name: Inject Python Snippet

on:
  push:
    paths:
      - 'snippets/*.py'

jobs:
  inject-snippet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set target .md from latest .py
        run: |
          LATEST_PY=$(ls -t snippets/*.py | head -n 1)
          BASENAME=$(basename "$LATEST_PY" .py)
          TARGET_MD="${BASENAME%%_*}.md"
          echo "TARGET_MD=$TARGET_MD" >> $GITHUB_ENV
          echo "BASENAME=$BASENAME" >> $GITHUB_ENV

      - name: Inject Python Snippet
        run: |
          python scripts/inject_snippet.py "$TARGET_MD"
          python scripts/inject_result.py "$RUN_PY"

      - name: Commit and Push if Changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $TARGET_MD
          git diff --cached --quiet || git commit -m "Auto update article with new snippet"
          git push
          
