name: Sync file to Gist
on:
  push:
    paths:
      - 'tools/*.py'

jobs:
  gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: Init
        run: |
          LATEST_PY=$(git diff --name-only HEAD^ HEAD | grep '^tools/.*\.py$')
          BASENAME=$(basename "$LATEST_PY")
          CONTENT=$(jq -Rs . < "$LATEST_PY")
          HIST_FILE="tools/gist-sync-history.log"
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "BASENAME=$BASENAME" >> $GITHUB_ENV
          echo "CONTENT=$CONTENT" >> $GITHUB_ENV
          echo "HIST_FILE=$HIST_FILE" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Excute
        run: |
          curl -s -w "%{http_code}" -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -d "{\"files\": {\"$BASENAME\": {\"content\": $CONTENT}}}" \
            https://api.github.com/gists/b69f770dbf52120e085b048cf0c66054
          echo "$TIMESTAMP - Updated: $BASENAME" >> "$HIST_FILE"

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "$HIST_FILE"
          git commit -m "Update $BASENAME (Gist sync completed)"
          git push
