name: Sync file to Gist
on:
  push:
    paths:
      - 'tools/*.py'

jobs:
  gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: Update Gist
        run: |
          LATEST_PY=$(git diff --name-only HEAD^ HEAD | grep '^tools/.*\.py$')
          BASENAME=$(basename "$LATEST_PY")
          CONTENT=$(jq -Rs . < "$LATEST_PY")
         
          RESPONSE=$(curl -s -w "%{http_code}" -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -d "{\"files\": {\"$BASENAME\": {\"content\": $CONTENT}}}" \
            https://api.github.com/gists/b69f770dbf52120e085b048cf0c66054)

          HTTP_STATUS="${RESPONSE: -3}"
          if [ "$HTTP_STATUS" = "200" ]; then
            echo "Gist sync succeeded for $BASENAME"
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add "$LATEST_PY"
            git commit -m "Update $BASENAME (Gist sync completed)"
          fi
