name: Sync file to Gist
on:
  push:
    paths:
      - 'tools/init.py'

jobs:
  gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Gist
        run: |
          CONTENT=$(jq -Rs . < tools/init.py)
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -d "{\"files\": {\"init.py\": {\"content\": $CONTENT}}}" \
            https://api.github.com/gists/b69f770dbf52120e085b048cf0c66054
