name: Sync file to Gist
on:
  push:
    paths:
      - 'tools/*.py'

jobs:
  gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: Update Gist
        run: |
          LATEST_PY=$(git diff --name-only HEAD^ HEAD | grep '^tools/.*\.py$')
          CONTENT=$(jq -Rs . < $LATEST_PY)
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -d "{\"files\": {\"init.py\": {\"content\": $CONTENT}}}" \
            https://api.github.com/gists/b69f770dbf52120e085b048cf0c66054
